anar/joins/urls.py
#coding: latin-1
from django.conf.urls import patterns, url
from django.views.generic import TemplateView, DetailView

from joins import views
import anarapp

urlpatterns = patterns('',    
    url(r'^$', views.index, name='index'),
    url(r'^cruce(?P<cruce_id>\d+)$', views.cruces, name='cruces'),
    url(r'^patrimonio$', anarapp.views.patrimonio),
    url(r'^quienes/', TemplateView.as_view(template_name="anarapp/quienes.html"),
	),

)

anar/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'anar.views.home', name='home'),
	# url(r'^anar/', include('anar.foo.urls')),
	# url(r'^yacimientos/$', 'anarapp.views.index'),
	# url(r'^mapa/$', 'geoespacial.views.mapa'),
	url(r'^', include('anarapp.urls')),
	url(r'^upload/(?P<path>.*)$','django.views.static.serve',
		{'document_root':settings.MEDIA_ROOT,}
	),

	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:        
	url(r'^admin/', include(admin.site.urls)),

	# Incluyendo los smarts selects
	url(r'^chaining/', include('smart_selects.urls')),
		
	# Incluyendo los cruces
	url(r'^cruces/', include('joins.urls', namespace='joins')),
	

)

anar/joins/models.py
from django.db import models

# Create your models here.

anar/joins/forms.py
# -*- coding: utf-8 -*-

from django import forms

########################################################################################
# Creando Cruces Yacimiento-Yacimiento Form
########################################################################################

OPCIONES_ESTADO = (
	('Amazonas'	, 'Amazonas'),
	('Anzoategui', 'Anzoategui'),
	('Apure', 'Apure'),
	('Aragua', 'Aragua'),
	('Barinas', 'Barinas'),
	('Bolívar', 'Bolívar'),
	('Carabobo', 'Carabobo'),
	('Cojedes', 'Cojedes'),
	('Delta Amacuro', 'Delta Amacuro'),
	('Falcón', 'Falcón'),
	('Guárico', 'Guárico'),
	('Lara', 'Lara'),
	('Mérida', 'Mérida'),
	('Miranda', 'Miranda'),
	('Monagas', 'Monagas'),
	('Nueva Esparta', 'Nueva Esparta'),
	('Portuguesa', 'Portuguesa'),
	('Sucre', 'Sucre'),
	('Tachira', 'Tachira'),
	('Trujillo', 'Trujillo'),
	('Vargas', 'Vargas'),
	('Yaracuy', 'Yaracuy'),
	('Zulia', 'Zulia'),
)

class CrucesYYForm(forms.Form):
    codigo 	= forms.CharField(required=False, max_length=20)
    estado = forms.ChoiceField(required=False, choices=OPCIONES_ESTADO)
    ubicacion = forms.CharField(required=False, max_length=20)
    carasurcopetrotipo = forms.CharField(required=False, max_length=50)
    material = forms.CharField(required=False, max_length=50)
    manifasociadas = forms.CharField(required=False, max_length=50)

    estado.widget.attrs 	= {'class':'chzn-select', 'data-placeholder':'Seleccione el estado'}

anar/joins/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponse
from joins.forms import CrucesYYForm
from django.shortcuts import render
from haystack.query import SearchQuerySet
from anarapp.models import Yacimiento

def index(request):
    form = CrucesYYForm()
    return render(request, 'joins/index.html', {'form' : form})
    

UBICACIONES = [
    '','Cerro','Cima','Ladera','Falda','Fila',
    'Pie de Monte','Barranco','Acantilado','Valle',
    'Río','Lecho','Margen Derecha',
    'Margen Izquierda','Isla','Raudal','Costa'       
]

ESTADOS = [
    'Amazonas', 'Anzoategui', 'Apure',
    'Aragua', 'Barinas', 'Bolívar',
    'Carabobo', 'Cojedes', 'Delta Amacuro',
    'Falcón', 'Guárico', 'Lara', 'Mérida',
    'Miranda', 'Monagas', 'Nueva Esparta', 
    'Portuguesa', 'Sucre', 'Tachira', 
    'Trujillo', 'Vargas', 'Yaracuy', 'Zulia'
]    

MANIFESTACIONES = [
        'Geoglifo',
        'Pintura Rupestre',
        'Petroglifo',
        'Petroglifo Pintado',
        'Micro-Petroglifo',
        'Piedra Mítica Natural',
        'Cerro Mítico Natural',
        'Cerro Mitico Natural con Petroglifo',
        'Cerro Mitico Natural Con Pintura',
        'Cerro Mitico Natural Con Dolmen',
        'Monumentos Megalíticos',
        'Monolitos',
        'Monolitos Con Grabados',
        'Menhires',
        'Menhires Con Puntos Acoplados',
        'Menhires Con Petroglifo',
        'Menhires Con Pintura',
        'Amolador',
        'Batea',
        'Puntos Acoplados',
        'Cupulas',
        'Mortero o Metate'
]

#Cuentos y cuales yacimientos hay en estado
def cruce1(form):
    sqs = SearchQuerySet()
    sqs = sqs.filter(estado = form.cleaned_data['estado'])
    total = sqs.count()

    estado = form.cleaned_data['estado']
    return {
        'total' : total, 
        'estado':estado, 
        'results':sqs}
#Bibliografia
def cruce27(form):
    yacimiento = Yacimiento.objects.get(codigo = form.cleaned_data['codigo'])
    codigo = form.cleaned_data['codigo'] 
    return {
        'codigo': codigo,
        'yacimiento': yacimiento,
    }
#Listar Dolmenes y menhires
def cruce8(form):
    sqs = SearchQuerySet()
    sqs = sqs.filter(pais = 'Venezuela').filter(tipo__in = [4, 5, 6, 7, 8])
    total = sqs.count()
    yacimientos = {}
    for estado in ESTADOS:
        lista = sqs.filter(estado = estado)
        yacimientos[estado] = lista
    return {
        'total' : total, 
        'yacimientos': yacimientos}

#Numero de piedras trabajadas a numeros de piedra en el yacimiento original
def cruce9(form):
    sqs = SearchQuerySet()
    sqs = sqs.filter(estado = form.cleaned_data['estado'])
    values = {}
    for e in sqs:
        try:
            values[e.__getattribute__('codigo')] = e.object.ConstitucionYacimiento 
        except:
            pass
    piedras = sum(0 if e.nroPiedras is None else e.nroPiedras for b,e in values.items())
    grabadas = sum(0 if e.nroPiedrasGrabadas is None else e.nroPiedrasGrabadas for b,e in values.items())
    pintadas = sum(0 if e.nroPiedrasPintadas is None else e.nroPiedrasPintadas for b,e in values.items())
    colocadas = sum(0 if e.nroPiedrasColocadas is None else e.nroPiedrasColocadas for b,e in values.items())

    return {
        'estado': sqs[0].estado,
        'piedras': piedras,
        'grabadas': grabadas,
        'pintadas': pintadas,
        'colocadas': colocadas,
        'yacimientos': sqs,
    }
#Listar la manifestacion por estado
def cruce10(form):
    #Revizar que este en el estado seleccionado
    if form.cleaned_data['codigo'] != '':
        sqs = SearchQuerySet()
        sqs = sqs.filter(estado = form.cleaned_data['estado']).filter(codigo = form.cleaned_data['codigo'])
        if sqs != []:
            for yac in sqs:
                if len(yac.manifestacion) != 0:
                    if yac.manifestacion[0].encode('utf8') != 'None':
                        if int(yac.manifestacion[0]) <= 22:
                            yac.manifestacion = MANIFESTACIONES[int(yac.manifestacion[0])]
            return {
            'yacimientos': sqs}

        else:
            return {
            'yacimientos': sqs}

    #Buscar en todo ese estado
    elif form.cleaned_data['codigo'] == '':
        sqs = SearchQuerySet()
        sqs = sqs.filter(estado = form.cleaned_data['estado'])
        for yac in sqs:
            if len(yac.manifestacion) != 0:
                if yac.manifestacion[0].encode('utf8') != 'None':
                    if int(yac.manifestacion[0]) <= 22:
                        yac.manifestacion = MANIFESTACIONES[int(yac.manifestacion[0])]

        return {
        'yacimientos': sqs}

#Listar la manifestacion por ubicacion
def cruce11(form):
    ubi = UBICACIONES.index(form.cleaned_data['ubicacion'])
    sqs = SearchQuerySet()
    sqs = sqs.filter(ubicacion = ubi).order_by('estado')
    yacimientos = {}
    for estado in ESTADOS:
        lista = sqs.filter(estado = estado)
        yacimientos[estado] = lista
        ubicaciones = {}
        for m in MANIFESTACIONES:
            ubicaciones[m] = len(lista.filter(manifestacion = MANIFESTACIONES.index(m)))
        yacimientos[estado] =  ubicaciones
    return {
            'ubi' : form.cleaned_data['ubicacion'],
            'yacimientos': yacimientos}

#listar ancho y profundidad de surco grabado, de petroglifos
def cruce12(form):
    sqs = SearchQuerySet()
    sqs = sqs.filter(pais = 'Venezuela').filter(manifestacion__in = [3, 4, 5])
    yacimientos = {}
    for estado in ESTADOS:
        lista = sqs.filter(estado = estado)
        yacimientos[estado] = lista
        for l in lista:
            l.carasurcopetroancho = l.carasurcopetroancho[0]
            l.carasurcopetroprofun = l.carasurcopetroprofun[0]

    return { 
        'yacimientos': yacimientos}

#Listar por estado los petroglifos con relieve
def cruce14(form):
    tipos = ['bajo relieve lineal',
    'bajo relieve planar',
    'bajo relieve planar y lineal',
    'alto relieve lineal',
    'alto relieve planar',
    'alto relieve planar y lineal',
    'bajo relieve planar y alto relieve planar',
    'bajo relieve planar y alto relieve lineal ',
    'bajo relieve lineal y alto relieve planar',
    'bajo relieve lineal y alto relieve lineal'

    ]
    list = []

    if form.cleaned_data['carasurcopetrotipo'].lower() == tipos[0].lower():
        list.append(5)
    if form.cleaned_data['carasurcopetrotipo'].lower() == tipos[1].lower():
        list.append(6)
    if form.cleaned_data['carasurcopetrotipo'].lower() == tipos[2].lower():
        list.append(6)
        list.append(5)
    if form.cleaned_data['carasurcopetrotipo'].lower() == tipos[3].lower():
        list.append(8)
    if form.cleaned_data['carasurcopetrotipo'].lower() == tipos[4].lower():
        list.append(9)
    if form.cleaned_data['carasurcopetrotipo'].lower() == tipos[5].lower():
        list.append(8)
        list.append(9)
    if form.cleaned_data['carasurcopetrotipo'].lower() == tipos[6].lower():
        list.append(6)
        list.append(9)
    if form.cleaned_data['carasurcopetrotipo'].lower() == tipos[7].lower():
        list.append(6)
        list.append(8)
    if form.cleaned_data['carasurcopetrotipo'].lower() == tipos[8].lower():
        list.append(5)
        list.append(9)
    if form.cleaned_data['carasurcopetrotipo'].lower() == tipos[9].lower():
        list.append(5)
        list.append(8)
    sqs = SearchQuerySet()
    sqs = sqs.filter(pais = 'Venezuela').filter(carasurcopetrotipo = list)
    yacimientos = {}
    total = sqs.count()
    for estado in ESTADOS:
        lista = sqs.filter(estado = estado)
        yacimientos[estado] = lista
    return { 
    'total':total,
    'tipo':form.cleaned_data['carasurcopetrotipo'],
    'yacimientos': yacimientos}

#petroglifos con aeras interlineadas
def cruce16(form):
    area = ['areas interlineales pulidas',
    'areas interlineales rebajadas',
    'grabados superpuestos',
    'grabados rebajados'
    ]          
    list = []

    list.append(area.index(form.cleaned_data['carasurcopetrotipo'].lower())+11)

    '''if form.cleaned_data['carasurcopetrotipo'].lower() == area[0].lower():
            list.append(11)
    elif form.cleaned_data['carasurcopetrotipo'].lower() == area[1].lower():
            list.append(12)
    elif form.cleaned_data['carasurcopetrotipo'].lower() == area[2].lower():
            list.append(13)
    elif form.cleaned_data['carasurcopetrotipo'].lower() == area[3].lower():
            list.append(14)'''
    sqs = SearchQuerySet()
    sqs = sqs.filter(pais = 'Venezuela').filter(carasurcopetrotipo = list,manifestacion__in = [3,4,5])
    return {'cruce':form.cleaned_data['carasurcopetrotipo'],
            'yacimientos': sqs}

#Roca del petroglifo
def cruce17(form):
    value = ''
    filters = ['roca ignea',
    'roca metamorfica',
    'roca sedimentaria',
    'erosion parcialmente moderada',
    'erosion parcialmente severa',
    'erosion extensiva moderada',
    'erosion extensiva severa'
    ]
    list = []

    list.append(filters.index(form.cleaned_data['material'].lower()) +1)

    if list[0] <=3 and 1 <= list[0]:
        value = 'material'
    else:
        value == 'conservacion'
        list[0] = list[0] -1

    '''if form.cleaned_data['material'].lower() == filters[0].lower:
        value = 'material'
        list.append(1)
    elif form.cleaned_data['material'].lower() == filters[1].lower:
        value = 'material'
        list.append(2)
    elif form.cleaned_data['material'].lower() == filters[2].lower:
        value = 'material'
        list.append(3)
    elif form.cleaned_data['material'].lower() == filters[3].lower:
        value = 'conservacion'
        list.append(3)
    elif form.cleaned_data['material'].lower() == filters[4].lower:
        value = 'conservacion'
        list.append(4)
    elif form.cleaned_data['material'].lower() == filters[5].lower:
        value = 'conservacion'
        list.append(5)
    elif form.cleaned_data['material'].lower() == filters[6].lower:
        value = 'conservacion'

anar/joins/templates/joins/cruce1.html
<!DOCTYPE html>
<html>
	<head>
		{% load staticfiles %}
		{% load url from future %}
		<title>Archivo Nacional de Arte Rupestre</title>
	
		<link rel="stylesheet" type="text/css" href="{% static 'anarapp/formstyle.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'anarapp/avanzada.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'anarapp/chosen.css' %}">
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		
		<script src="{% static 'anarapp/jquery-1.10.1.min.js' %}"></script>
		<script src="{% static 'anarapp/chosen.jquery.js' %}"></script>
		<script>
			$(document).ready(function(){$(".chzn-select").chosen({no_results_text: "Ningún resultado encontrado"})})
		</script>
		<style type="text/css">
			.chzn-container { width: 15em !important }
			input[type="text"] { border: 1px solid #AAA; padding: 5px }
			input[type="checkbox"] { margin-left: 100px !important }
			.chzn-search input { height: 25px !important }
		</style>
	</head>
<body>

	<ul id="nav">
		<li><a href="/">Inicio</a></li>
		<li><a href="#quienes">Quienes Somos</a></li>
		<li><a href="#patrimonio">Patrimonio Cultural Arqueológico</a></li>
		<li><a href="#programa">Programa de Educacion</a></li>
		<li><a href="#otros">Otros Servicios</a></li>
		<li><a href="#contacto">Contacto</a></li>
	</ul>

	<div id="banner">
		<div id="logo">
			<img src="{% static 'anarapp/logo.png' %}" height="75" width="200">
		</div>
	</div>

		
    <div style="width: 70%; margin: auto">

    <h1  id="titulo" style="font-size: 16pt"> ¿Cuántos y cuáles yacimientos hay en el estado {{ estado }}?</h1>
    <h2>Total de yacimientos: {{ total }}</h2>
    <ul>
        {% for result in results %}
            <li>Código: {{ result.codigo }},  <i>{{ result.nombre }}</i></li>
        {% endfor %}
    </ul>
</body>
</html>

anar/joins/templates/joins/index.html
<!DOCTYPE html>
<html>
	<head>
		{% load staticfiles %}
		{% load url from future %}
		<title>Archivo Nacional de Arte Rupestre</title>
	
		<link rel="stylesheet" type="text/css" href="{% static 'anarapp/formstyle.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'anarapp/avanzada.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'anarapp/chosen.css' %}">
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		
		<script src="{% static 'anarapp/jquery-1.10.1.min.js' %}"></script>
		<script src="{% static 'anarapp/chosen.jquery.js' %}"></script>
		<script>
			$(document).ready(function(){$(".chzn-select").chosen({no_results_text: "Ningún resultado encontrado"})})
		</script>
		<style type="text/css">
			.chzn-container { width: 15em !important }
			input[type="text"] { border: 1px solid #AAA; padding: 5px }
			input[type="checkbox"] { margin-left: 100px !important }
			.chzn-search input { height: 25px !important }
		</style>
	</head>
<body>

	<ul id="nav">
		<li><a href="/">Inicio</a></li>
		<li><a href="quienes">Quienes Somos</a></li>
		<li><a href="patrimonio">Patrimonio Cultural Arqueológico</a></li>
		<li><a href="#programa">Programa de Educacion</a></li>
		<li><a href="#otros">Otros Servicios</a></li>
		<li><a href="#contacto">Contacto</a></li>
	</ul>

	<div id="banner">
		<div id="logo">
			<img src="{% static 'anarapp/logo.png' %}" height="75" width="200">
		</div>
	</div>

		
    <div style="width: 70%; margin: auto">

    <h1  id="titulo" style="font-size: 16pt">Cruces  entre Yacimiento con Yacimiento</h1>
    <ul>
        <li>
            <strong>Cruce 1:</strong><br/>
            <p>
                ¿Cuántos y cuáles yacimientos hay en el siguiente estado?<br/>
                <form action="{% url 'joins:cruces' 1 %}">
                    <label>Estado: {{ form.estado }} </label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 2:</strong><br/>
            <p>
                ¿Qué nombre tiene el yacimiento con el siguiente código?<br/>
                <form action="{% url 'joins:cruces' 2 %}">
                    <label>Código: {{ form.codigo }} </label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 3:</strong><br/>
            <p>
                ¿Qué coordenadas tiene el yacimiento con el siguiente código?<br/>
                <form action="{% url 'joins:cruces' 3 %}">
                    <label>Código: {{ form.codigo }} </label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 4:</strong><br/>
            <p>
                ¿Qué apoyo bibliográfico tiene el yacimiento con el siguiente código?<br/>
                <form action="{% url 'joins:cruces' 4 %}">
                    <label>Código: {{ form.codigo }} </label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 5:</strong><br/>
            <p>
                ¿Qué gráficos tiene el yacimiento con el siguiente código?<br/>
                <form action="{% url 'joins:cruces' 5 %}">
                    <label>Código: {{ form.codigo }} </label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 6:</strong><br/>
            <p>
                ¿Qué material audiovisual tiene el yacimiento con el siguiente código?<br/>
                <form action="{% url 'joins:cruces' 6 %}">
                    <label>Código: {{ form.codigo }} </label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 7:</strong><br/>
            <p>
                ¿En qué páginas web aparece el yacimiento con el siguiente código?<br/>
                <form action="{% url 'joins:cruces' 7 %}">
                    <label>Código: {{ form.codigo }} </label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>        
        <li>
            <strong>Cruce 8:</strong><br/>
            <p>
                Listar todos los Dólmenes y Menhires en Venezuela y por estado:
                <br/>
                <form action="{% url 'joins:cruces' 8 %}">
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 9:</strong><br/>
            <p>
                Listar la proporción de número de piedras trabajadas a número de piedras en el yacimiento original en el siguiente estado:<br/>
                <form action="{% url 'joins:cruces' 9 %}">
                    <label>Estado: {{ form.estado }} </label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>        
        <li>
            <strong>Cruce 10:</strong><br/>
            <p>
                Listar todos los Geoglifos, Pinturas Rupestres, Micropetroglifos, Petroglifos, Petroglifos Pintados, Piedras Míticas Naturales, Cerros Miticos Naturales, Bateas, Menhires, Amoladores, Puntos Acoplados y Cúpulas en el siguiente yacimiento y estado:<br/>
                <form action="{% url 'joins:cruces' 10%}">
                    <label>Código: {{ form.codigo }} </label></br>
                <label>Estado: {{ form.estado }} </label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>        
        <li>
            <strong>Cruce 11:</strong><br/>
            <p>
                Listar por estado el total de Geoglifos, Pinturas Rupestres, Micropetroglifos, Petroglifos, Petroglifos Pintados, Piedras Míticas Naturales, Cerros Miticos Naturales, Bateas, Menhires, Amoladores, Puntos Acoplados y Cúpulas en la siguiente ubicación:<br/>
                <form action="{% url 'joins:cruces' 11 %}">
                    <label>Ubicación: {{form.ubicacion}}</label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>  
        <li>
            <strong>Cruce 12:</strong><br/>
            <p>
                Listar por estado el ancho y la profundidad del surco grabado para todos los yacimientos de Petroglifos<br/>
                <form action="{% url 'joins:cruces' 12%}">
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>  
        <li>
            <strong>Cruce 13:</strong><br/>
            <p>
                Para un mismo Ancho y/o Profundidad de surco, cuántos Petroglifos tienen:<br/>
                <form action="{% url 'joins:cruces' 13 %}">
                    <label>Ubicación: <input type="text"/></label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li> 
        <li>
            <strong>Cruce 14:</strong><br/>
            <p>
                Lísteme por estado cuántos y cuáles Petroglifos tienen :<br/>
                <form action="{% url 'joins:cruces' 14 %}">
                    <label>Caracteristica: {{form.carasurcopetrotipo}}</label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 15:</strong><br/>
            <p>
                Lísteme por estado, cuántas y cuáles Pinturas 
                Rupestres de todos los yacimientos tienen: <br/>
                <form action="{% url 'joins:cruces' 15 %}">
                    <label><input type="text"></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 16:</strong><br/>
            <p>
                Cuáles petroglifos tienen :<br/>
                <form action="{% url 'joins:cruces' 16 %}">
                    <label>Area/Grabado: {{form.carasurcopetrotipo}}</label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 17:</strong><br/>
            <p>
                Lísteme por estado, los petroglifos con:<br/>
                <form action="{% url 'joins:cruces' 17 %}">
                    <label>piedra/erosión: {{form.material}}</label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 18:</strong><br/>
            <p>
                Cuales pinturas rupestres por estado, con la siguiente combinacion tiene:<br/>
                <form action="{% url 'joins:cruces' 18 %}">
                    <label>piedra/erosión: {{form.material}}</label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
        <li>
            <strong>Cruce 19:</strong><br/>
            <p>
                Listema por codigo, estado y tipo de manifestacion los yacimientos que contengan manifestaciones asociadas de:<br/>
                <form action="{% url 'joins:cruces' 19 %}">
                    <label>Manifestacion asociada: {{form.manifasociadas}}</label></br></br>
                    <input type="submit" class="button" value="Consultar"/>
                </form>
            </p>
        </li>
                <li>
            <strong>Cruce 20:</strong><br/>
            <p>
                Lísteme por estado y yacimientos la proporcion de numero de piedras trabajadas a numero de piedras en el yacimientos original ubicadas en:<br/>
                <form action="{% url 'joins:cruces' 20 %}">
                    <label>Ubicacion: {{form.ubicacion}}</label></br></br>
                </form>
            </p>
        </li>
    </ul>
    	</div>
</body>